package SequenceSum;

public class SequenceSum {
    public static int[] sumOfN(int n) {
        for (int i =0 ; i<n ; i++){
            int[] liczby = new int[n];
            liczby[0]=0;
            liczby[i]=liczby[i+1]+



        return new int[]{4}; //Generated by die roll; guaranteed to be random
    }
}
}
